### ISSUE TITLE
animation is not stopping

### ISSUE THREAD

**Issue by dko6** [olesk75/AnimatedGIF#5]
Jakob Skjelten,
the animation start's very well, but the animation is not stopping.

root.mainloop()
 Stop Animate 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1545, in __call__
    return self.func(*args)
  File "AnimatedTest.py", line 30, in buttonPhotoClick
    lbl_with_my_gif.stop()  # Setting stop flag, which ends the update loop (animation)
TypeError: 'bool' object is not callable

**Comment by longk15t** [comment]
@dko6 I'm getting this issue, could you share the solution ? how to stop the animation of the gif ?

**Comment by olesk75** [comment]
Hi - I haven't seen this myself. Could it potentially be a Python 2.x issue? I've only tried this on Python 3.x. Could you try your code segmed on Python 3.x to see if that resolves this issue?

Also: it looks like lbl_with_my_gif is being overwritten which makes the stop() method fail, as there is no object to perform the method on - could you check the type of the lbl_with_my_gif object, with type(lbl_with_my_gif) before you try to call the stop() metho just to verify that it's not been overwritten at some point?
