### ISSUE TITLE
Nothing Happining 

### ISSUE THREAD

**Issue by devsanthoshmk** [olesk75/AnimatedGIF#8]
when i use the code as you mentioned nothing happens i just dont know where the gif is playing can you help me with this?

**Comment by olesk75** [comment]
Hi! I can certainly try, but it's not easy to do without a bit more context. Are you running it within a tkinter mainloop()? Are you trying the threaded or non-threaded approach?

**Comment by devsanthoshmk** [comment]
I'm really Sorry to bother i forgot change a gif name. i used customtkinter
